sudo: required
dist: trusty
language: cpp

# whitelist
branches:
  only:
    - master

install:
  - ls
  - mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
  - brew install cmake
  - ls
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian -y
  - sudo apt-get install libsdl-image1.2 libsdl-image1.2-dev -y
  - sudo apt-get install libsdl-net1.2 libsdl-net1.2-dev -y
  - sudo apt-get install libsdl-mixer1.2 libsdl-mixer1.2-dev -y
  - sudo apt-get install libsdl-ttf2.0 libsdl-ttf2.0-dev -y

compiler:
  - g++

script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make